name: Run Tests

on:
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      redis:
        image: redis:latest
        ports:
          - 6379:6379

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"

      - name: Install dependencies
        working-directory: ./back-end
        run: npm install

      - name: Run unit tests
        working-directory: ./back-end
        run: npm test
        env:
          NODE_ENV: test
          REDIS_URL: redis://localhost:6379
